### ISSUE TITLE
关于 build_dataset.py中 参数的设置问题

### ISSUE THREAD

**Issue by it-hao** [hkzhang91/HiNAS#1]
您好，谢谢开源，非常棒的工作。
我想知道 cfg.SEARCH.PORTION  这个参数的具体设置是怎样的，是论文中描述的 0.5 么？
还有 engineer 文件夹中 cfg.DATALOADER.R_CROP的设置  貌似都找不到 ，这些参数对数据集的处理应该都是很关键的。
期待您的回复，谢谢~

**Comment by hkzhang-git** [comment]
这个是yaml的用法，在one_stage_nas/config/defaults.py 文件里边，对各个参数都设置了默认值，如果，configs/xxx.yaml 文件里边没有重新设定参数，那么这个参数值就按照deafults.py里边的默认值设定的。

cfg.DATALOADER.R_CROP，这个参数对精度本身没有太多影响，它控制的是，是否从一张图像里截取多个patch,，这个主要是针对，内存不够大，需要频繁跟硬盘交互数据的情况下，cfg.DATALOADER.R_CROP设置大一点，能线性的增加训练速度（数据读取是瓶颈的话）。去噪，超分辨这种小数据集任务，这个参数作用不大。如果做亮度增强，see in dark，这个参数会有帮助。

**Comment by it-hao** [comment]
> 这个是yaml的用法，在one_stage_nas/config/defaults.py 文件里边，对各个参数都设置了默认值，如果，configs/xxx.yaml 文件里边没有重新设定参数，那么这个参数值就按照deafults.py里边的默认值设定的。
> 
> cfg.DATALOADER.R_CROP，这个参数对精度本身没有太多影响，它控制的是，是否从一张图像里截取多个patch,，这个主要是针对，内存不够大，需要频繁跟硬盘交互数据的情况下，cfg.DATALOADER.R_CROP设置大一点，能线性的增加训练速度（数据读取是瓶颈的话）。去噪，超分辨这种小数据集任务，这个参数作用不大。如果做亮度增强，see in dark，这个参数会有帮助。

**Comment by it-hao** [comment]
好的  我后面看代码的时候也看到了  谢谢
